name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
          cache-dependency-path: ui/pnpm-lock.yaml
      - name: Install Node Modules
        run: pnpm install --frozen-lockfile
        working-directory: ./ui
      - name: Build Application
        run: pnpm run build
        working-directory: ./ui
      - uses: vimtor/action-zip@v1
        with:
          files: fxmanifest.lua LICENSE.md README.md ui/dist client server shared config.lua
          recursive: false
          dest: feather-inventory.zip
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ui
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.package-version.outputs.current-version}}"
          prerelease: true
          title: "Release ${{ steps.package-version.outputs.current-version}}"
          files: |
            feather-inventory.zip
